language: 'go'

sudo: 'required'

go:
  - '1.9.2'

install:
  - 'sudo bash ./utils/main.sh'
  - 'make plugin'

script:
  - 'cd ./lib && sudo /home/travis/.gimme/versions/go/bin/go test -v'

notifications:
  email: false

