language: 'go'

services:
  - 'docker'

sudo: 'required'

go:
  - '1.9.2'

before_install:
  - './.travis/main.sh'

install:
  - 'sudo bash ./utils/create.sh'
  - 'sudo make plugin'

script:
  - 'make test'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      sudo make plugin-push ;
    fi

notifications:
  email: false

